[package]
name = "dotenv-rs-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
dotenv_rs = "0.16.1"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.11.0" }
napi-derive = "2.11.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true