/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function dotParseBase(path: string, prefix: string): Record<string, string | undefined | null>
export function getEnv(path: string, prefix: string): void
export function dotParse(path: string): Record<string, string | undefined | null>
